import { Josefin_Sans } from '@next/font/google'
import "./globals.css";

const jsoefin_sans = Josefin_Sans({ subsets: ["latin"],});

export const metadata = {
  title: "vegetable Wale Biil Book",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jsoefin_sans.className}>{children}</body>
    </html>
  );
}
